apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-rental-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-rental-server
  template:
    metadata:
      labels:
        app: grpc-rental-server
    spec:
      containers:
        - name: grpc-rental-server
          image: faruk5252/grpc-rental-server:0.5
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 50053
              name: grpc