apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-vehicle-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-vehicle-server
  template:
    metadata:
      labels:
        app: grpc-vehicle-server
    spec:
      containers:
        - name: grpc-vehicle-server
          image: farukismailoglu/grpc-vehicle-server
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 50051
              name: grpc